### ISSUE TITLE
Hilos en consola

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipoolaxd#1]
[practica 7[1].pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipoolaxd/files/15132398/practica.7.1.pdf)

**Comment by ElisabetRD** [comment]
16 tienen 7 ilustraciónes y falta desarrollo

**Comment by josealfredo79** [comment]
falta mucho a esta practica...
